### ISSUE TITLE
CI回す

### ISSUE THREAD

**Issue by kokoax** [gunkan-s/barnament#19]
とりあえずPRでたか知りたいからでたらslackに通知来るようにしたい

あと、test書け

**Comment by Fukasawawa** [comment]
通知何送る？

**Comment by kokoax** [comment]
CIじゃなくても良さげなので、そっちにissueをrefしてそっちでやろう

**Comment by kokoax** [comment]
refs: #20

**Comment by kokoax** [comment]
circle CI 回し始めました
