### ISSUE TITLE
GoFmt入れてほし見ある

### ISSUE THREAD

**Issue by kokoax** [gunkan-s/barnament#6]
golangはスタイルを自動で整形する(GoFmtを使う)のがデファクト
atomにも多分ライブラリがあるので、整形して、どうぞ

以下には、goimportってのが書いてあった
https://qiita.com/spiegel-im-spiegel/items/6c4c819207354c4d7262

atom使ってないからわからんけど、プラグインで遊んでみるといい
いろいろ捗るはず

**Comment by Fukasawawa** [comment]
できたので閉じます
